/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wwk_Xattrj */

#ifndef _Included_wwk_Xattrj
#define _Included_wwk_Xattrj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wwk_Xattrj
 * Method:    readAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_wwk_Xattrj_readAttribute
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     wwk_Xattrj
 * Method:    listAttributes
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_wwk_Xattrj_listAttributes
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wwk_Xattrj
 * Method:    writeAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_wwk_Xattrj_writeAttribute
  (JNIEnv *, jobject, jstring, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
